default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: ivan
  password: <%= ENV['TODO_APPLICATION_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: todo_application_development

test:
  <<: *default
  database: <%= ENV.fetch('PG_DATABASE', 'myapp_test') %>
  host:     <%= ENV.fetch('PG_HOST',  'localhost') %>
  username: <%= ENV.fetch('PG_USER', nil) %>
  password: <%= ENV.fetch('PG_PASSWORD', nil) %>
  port:     <%= ENV.fetch('PG_PORT', 5432) %>

production:
  <<: *default
  database: todo_application_production
  username: todo_application
  password: <%= ENV['TODO_APPLICATION_DATABASE_PASSWORD'] %>
